### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by rkeidar** [databus23/helm-diff#322] opened 2022-01-05 01:36 UTC
Our CI workflow install the diff plugin. Since an hour ago it start failing (commit 4790fb13b990e7cd146211ef22cb0f5fbbba4c57)
We are running:  

helm plugin install https://github.com/databus23/helm-diff

Error:

awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
Downloading 
curl: (3) URL using bad/illegal format or missing URL
Failed to install helm-diff
	For support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
Error: Process completed with exit code 1.

**Comment by michaeljguarino** [comment] 2022-01-05 01:56
I'm seeing this as well

**Comment by rkeidar** [comment] 2022-01-05 01:58
I work fine when you run it with specific version:
 helm plugin install https://github.com/databus23/helm-diff --version 3.1.3

**Comment by damienpontifex** [comment] 2022-01-05 03:36
I believe it is that latest commit from #267 
Running `helm plugin install https://github.com/databus23/helm-diff` locally fails. 
Whereas `helm plugin install https://github.com/databus23/helm-diff --version 97f77494396694beb878128430205888a91d70b4` succeeds (that is the second to last commit)

**Comment by damienpontifex** [comment] 2022-01-05 04:08
I think the `grep $ARCH` from https://github.com/databus23/helm-diff/blob/4790fb13b990e7cd146211ef22cb0f5fbbba4c57/install-binary.sh#L80-L84 is returning failure exit code because the latest release (3.1.3) doesn't have architecture specific artifacts (only OS specific) and hence `DOWNLOAD_URL` is empty after `getDownloadURL` call

**Comment by jBouyoud** [comment] 2022-01-05 10:38
Seems need a new [release](https://github.com/databus23/helm-diff#release-1)

**Comment by mumoshu** [comment] 2022-01-05 23:53
Just added arch-specific archives to the existing v3.1.3 release. I hope those fix the issue https://github.com/databus23/helm-diff/releases/tag/v3.1.3

**Comment by damienpontifex** [comment] 2022-01-06 00:11
Thanks @mumoshu to ensure I had a clean environment, I ran `helm plugin uninstall diff; sudo rm -r ~/Library/Caches/helm/plugins/https-github.com-databus23-helm-diff; helm plugin install https://github.com/databus23/helm-diff` and everything installed locally as expected :)

**Comment by mumoshu** [comment] 2022-01-06 00:26
@damienpontifex Glad to hear it worked! Thanks a lot for your confirmation ☺️

**Comment by koenpunt** [comment] 2022-01-07 09:46
> Just added arch-specific archives to the existing v3.1.3 release. I hope those fix the issue https://github.com/databus23/helm-diff/releases/tag/v3.1.3

This now causes new issues, where it has a download url consisting of multiple urls;

```
$ helm plugin install --debug https://github.com/databus23/helm-diff --version 97f77494396694beb878128430205888a91d70b4
[debug] vcs_installer.go:162: updating https://github.com/databus23/helm-diff
[debug] vcs_installer.go:152: setting version to "97f77494396694beb878128430205888a91d70b4"
[debug] vcs_installer.go:91: copying /Users/koenpunt/Library/Caches/helm/plugins/https-github.com-databus23-helm-diff to /Users/koenpunt/Library/helm/plugins/helm-diff
plugin_install.go:82: [debug] loading plugin from /Users/koenpunt/Library/helm/plugins/helm-diff
plugin.go:60: [debug] running install hook: /bin/sh -c $HELM_PLUGIN_DIR/install-binary.sh
Downloading https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-macos-amd64.tgz
https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-macos-arm64.tgz
https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-macos.tgz
curl: (3) URL using bad/illegal format or missing URL
Failed to install helm-diff
	For support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
helm.go:88: [debug] plugin install hook for "diff" exited with error
main.runHook
	helm.sh/helm/v3/cmd/helm/plugin.go:67
main.(*pluginInstallOptions).run
	helm.sh/helm/v3/cmd/helm/plugin_install.go:88
main.newPluginInstallCmd.func3
	helm.sh/helm/v3/cmd/helm/plugin_install.go:59
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_arm64.s:1133
```

**Comment by mumoshu** [comment] 2022-01-07 10:01
@koenpunt Thanks for reporting! In that case you can just replace `97f77494396694beb878128430205888a91d70b4` with `v3.1.3` in the helm plugin install command, as it's really the same for helm-diff.

Specifying `97f77494396694beb878128430205888a91d70b4` results in grabbing `plugin.yaml` for that commit, which may result in downloading the version of helm-diff that corresponds to the version number embedded in the `plugin.yaml`, which is `3.1.3` in this case.

https://github.com/databus23/helm-diff/blob/97f77494396694beb878128430205888a91d70b4/plugin.yaml#L4

**Comment by koenpunt** [comment] 2022-01-07 10:07
> In that case you can just replace `97f77494396694beb878128430205888a91d70b4` with `v3.1.3`

I did that for now, but it should be possible to use a single commit as well? Or at least the script should be able to resolve to a single download url I suppose?

**Comment by stitakis** [comment] 2022-01-07 15:59
@mumoshu the installation is failing for us.... we are installing in a docker container based on `openshift/jenkins-slave-base-centos7`

this is the run command:
```
RUN cd /tmp \
    && mkdir -p /tmp/helm \
    && curl -LO https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz \
    && tar -zxvf helm-v3.4.1-linux-amd64.tar.gz -C /tmp/helm \
    && mv /tmp/helm/linux-amd64/helm /usr/local/bin/helm \
    && chmod a+x /usr/local/bin/helm \
    && helm version \
    && helm plugin install --debug https://github.com/databus23/helm-diff --version v3.1.3 \
    && helm plugin install --debug https://github.com/jkroepke/helm-secrets --version v3.3.5 \
    && sops --version \
    && rm -rf /tmp/helm
```

these are the logs:
``` 
Step 16/26 : RUN cd /tmp     && mkdir -p /tmp/helm     && curl -LO https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz     && tar -zxvf helm-v3.4.1-linux-amd64.tar.gz -C /tmp/helm     && mv /tmp/helm/linux-amd64/helm /usr/local/bin/helm     && chmod a+x /usr/local/bin/helm     && helm version     && helm plugin install --debug https://github.com/databus23/helm-diff --version v3.1.3     && helm plugin install --debug https://github.com/jkroepke/helm-secrets --version v3.3.5     && sops --version     && rm -rf /tmp/helm
 ---> Running in e7563534409d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.7M  100 12.7M    0     0  22.6M      0 --:--:-- --:--:-- --:--:-- 22.7M
linux-amd64/
linux-amd64/LICENSE
linux-amd64/README.md
linux-amd64/helm
W0107 15:56:17.894930      15 loader.go:223] Config not found: /var/lib/origin/openshift.local.config/master/admin.kubeconfig
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
W0107 15:56:17.944550      26 loader.go:223] Config not found: /var/lib/origin/openshift.local.config/master/admin.kubeconfig
[debug] vcs_installer.go:159: cloning https://github.com/databus23/helm-diff to /home/jenkins/.cache/helm/plugins/https-github.com-databus23-helm-diff
[debug] vcs_installer.go:152: setting version to "v3.1.3"
[debug] vcs_installer.go:91: copying /home/jenkins/.cache/helm/plugins/https-github.com-databus23-helm-diff to /home/jenkins/.local/share/helm/plugins/helm-diff
plugin_install.go:82: [debug] loading plugin from /home/jenkins/.local/share/helm/plugins/helm-diff
plugin.go:61: [debug] running install hook: /usr/bin/sh -c $HELM_PLUGIN_DIR/install-binary.sh
W0107 15:56:19.034371      26 loader.go:223] Config not found: /var/lib/origin/openshift.local.config/master/admin.kubeconfig
W0107 15:56:19.084887     145 loader.go:223] Config not found: /var/lib/origin/openshift.local.config/master/admin.kubeconfig
Downloading https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-linux-amd64.tgz
https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-linux-arm64.tgz
https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-linux.tgz
curl: (3) Illegal characters found in URL
Failed to install helm-diff
	For support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
helm.go:81: [debug] plugin install hook for "diff" exited with error
main.runHook
	/home/circleci/helm.sh/helm/cmd/helm/plugin.go:68
main.(*pluginInstallOptions).run
	/home/circleci/helm.sh/helm/cmd/helm/plugin_install.go:88
main.newPluginInstallCmd.func3
	/home/circleci/helm.sh/helm/cmd/helm/plugin_install.go:59
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
The command '/bin/bash -o pipefail -c cd /tmp     && mkdir -p /tmp/helm     && curl -LO https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz     && tar -zxvf helm-v3.4.1-linux-amd64.tar.gz -C /tmp/helm     && mv /tmp/helm/linux-amd64/helm /usr/local/bin/helm     && chmod a+x /usr/local/bin/helm     && helm version     && helm plugin install --debug https://github.com/databus23/helm-diff --version v3.1.3     && helm plugin install --debug https://github.com/jkroepke/helm-secrets --version v3.3.5     && sops --version     && rm -rf /tmp/helm' returned a non-zero code: 1
```

**Comment by koenpunt** [comment] 2022-01-07 16:30
@stitakis same issue what I [reported above](https://github.com/databus23/helm-diff/issues/322#issuecomment-1007271215). It resolves multiple urls from the GitHub api, but treats them as a single url, causing the `Illegal characters found in URL` message.

**Comment by mumoshu** [comment] 2022-01-08 07:12
> I did that for now, but it should be possible to use a single commit as well? Or at least the script should be able to resolve to a single download url I suppose?

@koenpunt Thanks for the feedback. But I'm pretty confused- how is that possible? We don't build helm-diff for every commit made to our main branch so allowing to install helm-diff from a commit ID implies that we need to enhance our plugin installation script to use `go build` to build helm-diff from an arbitrary commit.

Does your environment where you run helm and helm-diff has `go` installed?

**Comment by mumoshu** [comment] 2022-01-08 07:18
@stitakis @koenpunt Ah, so it looks like specifying `v3.1.3` now results in `helm plugin install` to grab the `plugin.yaml` and the installation script from the `v3.1.3` tag of helm-diff repo, which doesn't support new arch-specific release assets?

Probably what we'd need to do instead would be to undo addition of arch-specific release assets to `v3.1.3` AND cut a new release (like `v3.2.0`) that has only arch-specific artifacts?

**Comment by mumoshu** [comment] 2022-01-08 07:25
Hm, it works for me on linux/amd64 + 3.1.3

```
$ helm plugin install --debug https://github.com/databus23/helm-diff --version v3.1.3

[debug] vcs_installer.go:162: updating https://github.com/databus23/helm-diff
[debug] vcs_installer.go:152: setting version to "v3.1.3"
[debug] vcs_installer.go:91: copying /home/mumoshu/.cache/helm/plugins/https-github.com-databus23-helm-diff to /home/mumoshu/.local/share/helm/plugins/helm-diff
plugin_install.go:82: [debug] loading plugin from /home/mumoshu/.local/share/helm/plugins/helm-diff
plugin.go:60: [debug] running install hook: /usr/bin/sh -c $HELM_PLUGIN_DIR/install-binary.sh
Downloading https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-linux.tgz
```

**Comment by mumoshu** [comment] 2022-01-08 07:41
I've done https://github.com/databus23/helm-diff/issues/322#issuecomment-1007900888 anyway and verified the below works for me.

```
# install from master (results in installing 3.2.0)
$ helm plugin install --debug https://github.com/databus23/helm-diff

# 3.1.3

$ helm plugin remove diff
$ helm plugin install --debug https://github.com/databus23/helm-diff --version 3.1.3


# v3.1.3

$ helm plugin remove diff
$ helm plugin install --debug https://github.com/databus23/helm-diff --version v3.1.3

# 3.2.0

$ helm plugin remove diff
$ helm plugin install --debug https://github.com/databus23/helm-diff --version 3.2.0

# v3.2.0

$ helm plugin remove diff
$ helm plugin install --debug https://github.com/databus23/helm-diff --version v3.2.0

```

**Comment by koenpunt** [comment] 2022-01-08 08:01
> But I'm pretty confused- how is that possible? We don't build helm-diff for every commit made to our main branch.

Yeah I noticed that, but the download script still is resolving the download url incorrectly. 

That said, If using a commit hash is not really supported, should it maybe fail immediately, instead of downloading the latest release?

**Comment by mumoshu** [comment] 2022-01-08 08:19
> That said, If using a commit hash is not really supported, should it maybe fail immediately, instead of downloading the latest release?

@koenpunt Yeah, maybe that's better!

**Comment by clemensutschig** [comment] 2022-01-09 08:56
hmmm - this is from today morning (our CI) ... (as @stitakis noted above)

```
[2022-01-09T02:37:54.301Z] [0;32m    amazon-ebs:  ---> Running in baf9281642ed[0m
[2022-01-09T02:37:54.301Z] [0;32m    amazon-ebs: [91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current[0m
[2022-01-09T02:37:54.301Z] [0;32m    amazon-ebs:    [0m[91m                           [0m[91m   Dload  Upload   T[0m[91motal   Spent    Left[0m[91m  Speed[0m
[2022-01-09T02:37:55.238Z] [0;32m    amazon-ebs: 100 12.7M  100 12.7M    0     0  12.8M      0 --:--:-- --:--:-- --:--:-- 12.8M[0m
[2022-01-09T02:37:55.238Z] [0;32m    amazon-ebs: [0mlinux-amd64/[0m
[2022-01-09T02:37:55.238Z] [0;32m    amazon-ebs: linux-amd64/LICENSE[0m
[2022-01-09T02:37:55.238Z] [0;32m    amazon-ebs: linux-amd64/README.md[0m
[2022-01-09T02:37:55.238Z] [0;32m    amazon-ebs: linux-amd64/helm[0m
[2022-01-09T02:37:56.170Z] [0;32m    amazon-ebs: version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}[0m
[2022-01-09T02:37:58.070Z] [0;32m    amazon-ebs: Downloading https://github.com/databus23/helm-diff/releases/download/v3.2.0/helm-diff-linux-amd64.tgz[0m
[2022-01-09T02:37:58.070Z] [0;32m    amazon-ebs: https://github.com/databus23/helm-diff/releases/download/v3.2.0/helm-diff-linux-arm64.tgz[0m
[2022-01-09T02:37:58.070Z] [0;32m    amazon-ebs: [91mcurl: (3) Illegal characters found in URL[0m
[2022-01-09T02:37:58.070Z] [0;32m    amazon-ebs: [0mFailed to install helm-diff[0m
[2022-01-09T02:37:58.070Z] [0;32m    amazon-ebs: 	For support, go to https://github.com/databus23/helm-diff.[0m
[2022-01-09T02:37:58.070Z] [0;32m    amazon-ebs: [91mError: plugin install hook for "diff" exited with error[0m
```

and this worked, untouched a few days back ... so I guess it's a regression?!

**Comment by mumoshu** [comment] 2022-01-09 09:05
@clemensutschig Intesresting.. The below shows how it succeeds for me, and I see no meaningful diff between your logs and mine:

<details>

```
$ rm -rf ~/.cache/helm/plugins/https-github.com-databus23-helm-diff/mumoshu@m75q2a:~/p/helm-diff$ helm plugin remove diff
Uninstalled plugin: diff
mumoshu@m75q2a:~/p/helm-diff$ helm plugin install --debug https://github.com/databus23/helm-diff
[debug] vcs_installer.go:159: cloning https://github.com/databus23/helm-diff to /home/mumoshu/.cache/helm/plugins/https-github.com-databus23-helm-diff
[debug] vcs_installer.go:91: copying /home/mumoshu/.cache/helm/plugins/https-github.com-databus23-helm-diff to /home/mumoshu/.local/share/helm/plugins/helm-diff
plugin_install.go:82: [debug] loading plugin from /home/mumoshu/.local/share/helm/plugins/helm-diff
plugin.go:60: [debug] running install hook: /usr/bin/sh -c $HELM_PLUGIN_DIR/install-binary.sh
Error: unknown command "home" for "helm"
Run 'helm --help' for usage.
Downloading https://github.com/databus23/helm-diff/releases/latest/download/helm-diff-linux-amd64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- -100   155  100   155    0     0    527      0 --:--:-- --:--:-- --:--:--   527
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- -100   662  100   662    0     0   1287      0 --:--:-- --:--:-- --:--:--  646k
 56 14.3M   56 8272k    0     0  5540k      0  0:00:02  0:00:01  100 14.3M  100 14.3M    0     0  8620k      0  0:00:01  0:00:01 --:--:-- 30.1M
diff/
diff/README.md
diff/plugin.yaml
diff/LICENSE
diff/bin/
diff/bin/diff
Preparing to install into /home/mumoshu/.local/share/helm/plugins/helm-diff
helm-diff installed into /home/mumoshu/.local/share/helm/plugins/helm-diff/helm-diff

The Helm Diff Plugin

* Shows a diff explaining what a helm upgrade would change:
    This fetches the currently deployed version of a release
  and compares it to a local chart plus values. This can be 
  used visualize what changes a helm upgrade will perform.

* Shows a diff explaining what had changed between two revisions:
    This fetches previously deployed versions of a release
  and compares them. This can be used visualize what changes 
  were made during revision change.

* Shows a diff explaining what a helm rollback would change:
    This fetches the currently deployed version of a release
  and compares it to adeployed versions of a release, that you 
  want to rollback. This can be used visualize what changes a 
  helm rollback will perform.

Usage:
  diff [flags]
  diff [command]

Available Commands:
  release     Shows diff between release's manifests
  revision    Shows diff between revision's manifests
  rollback    Show a diff explaining what a helm rollback could perform
  upgrade     Show a diff explaining what a helm upgrade would change.
  version     Show version of the helm diff plugin

Flags:
      --allow-unreleased             enables diffing of releases that are not yet deployed via Helm
  -C, --context int                  output NUM lines of context around changes (default -1)
      --detailed-exitcode            return a non-zero exit code when there are changes
      --devel                        use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored.
      --disable-openapi-validation   disables rendered templates validation against the Kubernetes OpenAPI Schema
      --disable-validation           disables rendered templates validation against the Kubernetes cluster you are currently pointing to. This is the same validation performed on an install
      --dry-run                      disables cluster access and show diff as if it was install. Implies --install, --reset-values, and --disable-validation
  -h, --help                         help for diff
      --include-tests                enable the diffing of the helm test hooks
      --install                      enables diffing of releases that are not yet deployed via Helm (equivalent to --allow-unreleased, added to match "helm upgrade --install" command
      --kubeconfig string            This flag is ignored, to allow passing of this top level flag to helm
      --no-color                     remove colors from the output
      --no-hooks                     disable diffing of hooks
      --normalize-manifests          normalize manifests before running diff to exclude style differences from the output
      --output string                Possible values: diff, simple, json, template. When set to "template", use the env var HELM_DIFF_TPL to specify the template. (default "diff")
      --post-renderer string         the path to an executable to be used for post rendering. If it exists in $PATH, the binary will be used, otherwise it will try to look for the executable at the given path
      --repo string                  specify the chart repository url to locate the requested chart
      --reset-values                 reset the values to the ones built into the chart and merge in any new values
      --reuse-values                 reuse the last release's values and merge in any new values. If '--reset-values' is specified, this is ignored
      --set stringArray              set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray         set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray       set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --show-secrets                 do not redact secret values in the output
      --strip-trailing-cr            strip trailing carriage return on input
      --suppress stringArray         allows suppression of the values listed in the diff output
  -q, --suppress-secrets             suppress secrets in the output
  -f, --values valueFiles            specify values in a YAML file (can specify multiple) (default [])
      --version string               specify the exact chart version to use. If this is not specified, the latest version is used

Additional help topics:
  diff          

Use "diff [command] --help" for more information about a command.
Installed plugin: diff
```
</details>

**Comment by mumoshu** [comment] 2022-01-09 09:08
> hmmm - this is from today morning (our CI) ... (as @stitakis noted above)

FWIW, @stitakis's was `helm plugin install --debug https://github.com/databus23/helm-diff --version v3.1.3` which should work now because we've removed "redundant" arch-specific archives out of the 3.1.3 release.

Perhaps you're running a different command? Do you have a `--version` flag specified?

**Comment by mumoshu** [comment] 2022-01-09 09:10
@clemensutschig Maybe you've specified a commit ID in `--version`? It isn't supported and it doesn't actually work as you might have expected.

**Comment by clemensutschig** [comment] 2022-01-09 09:16
@mumoshu  - nope -we run 

```
  && helm plugin install https://github.com/databus23/helm-diff --version v${HELM_PLUGIN_DIFF_VERSION} \
```
with 
```
HELM_PLUGIN_DIFF_VERSION=3.1.3
``` 
on top of `3.4.1` - that we install with

```
    && curl -LO https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
    && tar -zxvf helm-v${HELM_VERSION}-linux-amd64.tar.gz -C /tmp/helm \
    && mv /tmp/helm/linux-amd64/helm /usr/local/bin/helm \
    && chmod a+x /usr/local/bin/helm \
``` 

and all that on top of centos (jenkins-agent)

**Comment by mumoshu** [comment] 2022-01-09 09:24
@clemensutschig Thsi is how it succeeds for me with `--version v3.1.3`

<details>

```
$ helm plugin install --debug https://github.com/databus23/helm-diff --version v3.1.3
[debug] vcs_installer.go:159: cloning https://github.com/databus23/helm-diff to /home/mumoshu/.cache/helm/plugins/https-github.com-databus23-helm-diff
[debug] vcs_installer.go:152: setting version to "v3.1.3"
[debug] vcs_installer.go:91: copying /home/mumoshu/.cache/helm/plugins/https-github.com-databus23-helm-diff to /home/mumoshu/.local/share/helm/plugins/helm-diff
plugin_install.go:82: [debug] loading plugin from /home/mumoshu/.local/share/helm/plugins/helm-diff
plugin.go:60: [debug] running install hook: /usr/bin/sh -c $HELM_PLUGIN_DIR/install-binary.sh
Downloading https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-linux.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- -100   656  100   656    0     0   2285      0 --:--:-- --:--:-- --:--:--  2285
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- - 80 14.9M   80 12.0M    0     0  9467k      0  0:00:01  0:00:01 -100 14.9M  100 14.9M    0     0   9.8M      0  0:00:01  0:00:01 --:--:-- 12.3M
Preparing to install into /home/mumoshu/.local/share/helm/plugins/helm-diff
helm-diff installed into /home/mumoshu/.local/share/helm/plugins/helm-diff/helm-diff

The Helm Diff Plugin

* Shows a diff explaining what a helm upgrade would change:
    This fetches the currently deployed version of a release
  and compares it to a local chart plus values. This can be 
  used visualize what changes a helm upgrade will perform.

* Shows a diff explaining what had changed between two revisions:
    This fetches previously deployed versions of a release
  and compares them. This can be used visualize what changes 
  were made during revision change.

* Shows a diff explaining what a helm rollback would change:
    This fetches the currently deployed version of a release
  and compares it to adeployed versions of a release, that you 
  want to rollback. This can be used visualize what changes a 
  helm rollback will perform.

Usage:
  diff [flags]
  diff [command]

Available Commands:
  release     Shows diff between release's manifests
  revision    Shows diff between revision's manifests
  rollback    Show a diff explaining what a helm rollback could perform
  upgrade     Show a diff explaining what a helm upgrade would change.
  version     Show version of the helm diff plugin

Flags:
      --allow-unreleased             enables diffing of releases that are not yet deployed via Helm
  -C, --context int                  output NUM lines of context around changes (default -1)
      --detailed-exitcode            return a non-zero exit code when there are changes
      --devel                        use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored.
      --disable-openapi-validation   disables rendered templates validation against the Kubernetes OpenAPI Schema
      --disable-validation           disables rendered templates validation against the Kubernetes cluster you are currently pointing to. This is the same validation performed on an install
      --dry-run                      disables cluster access and show diff as if it was install. Implies --install, --reset-values, and --disable-validation
  -h, --help                         help for diff
      --include-tests                enable the diffing of the helm test hooks
      --install                      enables diffing of releases that are not yet deployed via Helm (equivalent to --allow-unreleased, added to match "helm upgrade --install" command
      --kubeconfig string            This flag is ignored, to allow passing of this top level flag to helm
      --no-color                     remove colors from the output
      --no-hooks                     disable diffing of hooks
      --output string                Possible values: diff, simple, json, template. When set to "template", use the env var HELM_DIFF_TPL to specify the template. (default "diff")
      --post-renderer string         the path to an executable to be used for post rendering. If it exists in $PATH, the binary will be used, otherwise it will try to look for the executable at the given path
      --reset-values                 reset the values to the ones built into the chart and merge in any new values
      --reuse-values                 reuse the last release's values and merge in any new values. If '--reset-values' is specified, this is ignored
      --set stringArray              set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray         set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray       set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --show-secrets                 do not redact secret values in the output
      --suppress stringArray         allows suppression of the values listed in the diff output
  -q, --suppress-secrets             suppress secrets in the output
  -f, --values valueFiles            specify values in a YAML file (can specify multiple) (default [])
      --version string               specify the exact chart version to use. If this is not specified, the latest version is used

Additional help topics:
  diff          

Use "diff [command] --help" for more information about a command.
Installed plugin: diff
```
</details>

> but ... (edited) ... what looks weird to me - is why is it trying 3.2.0?

This usually happens when you've outdated helm plugins cache. I tend to clean it up before running `helm plugin install` by running:

```
rm -rf ~/.cache/helm/plugins/https-github.com-databus23-helm-diff/
```

and the plugins cache path comes from the output of `helm env`. Maybe adding `helm env` before the install-plugin command and also `find $THE_PLUGINS_CACHE_PATH` would reveal something useful?

**Comment by clemensutschig** [comment] 2022-01-09 09:27
It's a plain fresh install - so there should not be any cache ... @stitakis can you try this tmrw please?

**Comment by mumoshu** [comment] 2022-01-09 09:27
At least, the below log implies that `helm` is using outdated `install-binary.sh` (which doesn't have support for new arch-specific archives available since 3.2.0) to install 3.2.0. AFAIK, that cannot happen without corrupted plugin cache.

```
[2022-01-09T02:37:58.070Z] �[0;32m    amazon-ebs: Downloading https://github.com/databus23/helm-diff/releases/download/v3.2.0/helm-diff-linux-amd64.tgz�[0m
[2022-01-09T02:37:58.070Z] �[0;32m    amazon-ebs: https://github.com/databus23/helm-diff/releases/download/v3.2.0/helm-diff-linux-arm64.tgz�[0m
```

See `HELM_CACHE_HOME` value in the `helm env` output. If you're configuring your CI system to cache that path, it can break like that.

**Comment by mumoshu** [comment] 2022-01-09 09:35
In case it turned out to be outdated plugin cache issue- our `install-binary.sh` is only backward-compatible(not forward-compatible) so this kind of issue is unavoidable. In other words, if you do want a real solid helm plugin installation step in your CI, I'd say you shouldn't cache `${HELM_CACHE_HOME}/plugins`.

**Comment by clemensutschig** [comment] 2022-01-09 10:16
ok deleting with `rm -rf $HOME/.cache/helm/plugins/https-github.com-databus23-helm-diff || true` does not help ... :(

from helm env
```
HELM_BIN="helm"
HELM_CACHE_HOME="/home/jenkins/.cache/helm"
HELM_CONFIG_HOME="/home/jenkins/.config/helm"
HELM_DATA_HOME="/home/jenkins/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="default"
HELM_PLUGINS="/home/jenkins/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/home/jenkins/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/home/jenkins/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/home/jenkins/.config/helm/repositories.yaml"
```

**Comment by mumoshu** [comment] 2022-01-09 10:23
@clemensutschig Could you try running `git show --oneline --stat` in both `$HOME/.cache/helm/plugins/https-github.com-databus23-helm-diff` and `$HOME/.local/share/helm/plugins/helm-diff/` respectively after the helm plugin installation failure to see what's happening?

**Comment by mumoshu** [comment] 2022-01-09 10:24
I'm currently using Helm 3.5.3 so try upgrading helm if that makes difference.

**Comment by mumoshu** [comment] 2022-01-09 10:32
Please see the relevant part of install-binary.sh across versions below:

## `--version 3.1.3`

https://github.com/databus23/helm-diff/blob/b80187ead436678d1f4f9137c26d23ca04eef353/install-binary.sh#L72-L83 

installs 3.1.3 by `grep $OS | grep $ARCH` + https://github.com/databus23/helm-diff/releases/tag/v3.1.3

## `--version 3.2.0`

https://github.com/databus23/helm-diff/blob/860f354d93fb5024d5fa947544e5f9e6a0907f32/install-binary.sh#L72-L83 

installs 3.2.0 by `grep $OS | grep $ARCH` + https://github.com/databus23/helm-diff/releases/tag/v3.2.0

## without `--version`

It will use the script at the HEAD of the master branch

https://github.com/databus23/helm-diff/blob/74864723d4503815d267794341ab87a3ba3d16c3/install-binary.sh#L85-L89 

installs 3.2.0 today thanks to L89

**Comment by michaelsauter** [comment] 2022-01-10 08:57
So I did some more debugging around this.

The error mentioned by @clemensutschig happens with Helm 3.4.2. Updating Helm to 3.5.3 and helm-diff to 3.2.0 fixes the problem. I am not sure what change in Helm 3.5.3 is responsible for this, but I think we can update to 3.5.3.

However, the install displays that it doesn't install version 3.2.0, but rather 3.3.1. I investigated this as it simply seems to install the latest version, no matter what is passed via `--version v<VERSION>`. I realised that the install script is actually broken until https://github.com/databus23/helm-diff/pull/307. The issue was the following line:

```
: ${HELM_PLUGIN_DIR:="$("${HELM_BIN}" home --debug=false)/plugins/helm-diff"}
```

`home` is not a valid Helm command (neither in the 3.5.x line nor in the latest 3.7.2). Because the script does not exit on error, it continues, but with `HELM_PLUGIN_DIR` being `/plugins/helm-diff`. Because that path doesn't exist, `version=$(git -C "$HELM_PLUGIN_DIR" describe --tags --exact-match 2>/dev/null || :)` returns nothing, which leads to the latest version being downloaded.

The latest version of `helm-diff`, 3.3.1, works correctly, however only in systems which support `which`, which is not POSIX compatible (see e.g. https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script) and consequently fails on UBI images for example.

I'm going to provide a fix for this in a sec.

**Comment by mumoshu** [comment] 2022-01-10 09:03
> which is not POSIX compatible

😱

**Comment by mumoshu** [comment] 2022-01-10 09:44
3.3.2 has been released with the fix. Would you mind trying once again?

**Comment by michaelsauter** [comment] 2022-01-10 12:24
@mumoshu It works now, thank you very much!

**Comment by mumoshu** [comment] 2022-01-10 12:30
@michaelsauter Thank you for your help!

**Comment by Hammond95** [comment] 2022-01-12 22:37
@michaelsauter Thank you for spotting that, I have included the line using which, didn't thought about the POSIX compatibility.

On the other hand the home command was already in the script, and I kept it for back compatibility with helm2.

Not sure it would still work for helm2 without that line.

**Comment by mumoshu** [comment] 2022-01-22 08:11
@rkeidar I hope it's already fixed for you too and you're having happy days.

Closing as resolved.
Thank you everyone for your support!

P.S. I'm willing to add Alpine Linux and Busybox to our test matrix (#347). Your contribution is much appreciated!

**Closed by mumoshu** 2022-01-22 08:11 UTC
