### ISSUE TITLE
installation falling due to var $arch is introduced

### ISSUE THREAD

**Issue by jitendrasinghsendhav** [databus23/helm-diff#324] opened 2022-01-05 09:59 UTC
https://github.com/databus23/helm-diff/commit/4790fb13b990e7cd146211ef22cb0f5fbbba4c57?diff=split#diff-84b911b5c187acb3fa01e487f0e0fda54285d6d67d5d630993bab014e4d8c942L79
    
     "browser_download_url": "https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-linux.tgz"

**Comment by t0p4** [comment] 2022-01-05 10:35
The same issue

**Comment by jitendrasinghsendhav** [comment] 2022-01-05 10:46
quick fix is to not use latest version, I changed master to latest tag(v3.1.3) it worked 

helm plugin install https://github.com/databus23/helm-diff --version master

helm plugin install https://github.com/databus23/helm-diff --version v3.1.3

**Comment by jakubbujny** [comment] 2022-01-05 15:18
We are facing the issue as well

**Comment by mumoshu** [comment] 2022-01-05 23:33
Closing as a dupe of #324. I'm going to add the new arch specific archives to the existing v3.1.3 release to see if it resolves the issue

**Closed by mumoshu** 2022-01-05 23:33 UTC
