### ISSUE TITLE
Helm diff plugin doesn't work with dependencies charts

### ISSUE THREAD

**Issue by firehist** [databus23/helm-diff#300] opened 2021-08-12 12:05 UTC
Hello everybody,

First of all, thanks for the work 👏💪

I have a chart which use an other chart as a dependency.
When I override values for the dependency chart, the diff doesn't output any changes incoming, which is different from the upgrade command which applies well the changes.

Does the dependencies are handled by this awesome plugin?

To help the investigations, I created a simple repository to show the structure:
https://github.com/firehist/helm-diff-dependencies

Here are versions:
```
➜ helm3 version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"

➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-gke.501", GitCommit:"de876a981b936ce528482c45794fb1dfc5005042", GitTreeState:"clean", BuildDate:"2021-06-25T02:54:31Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

helm-diff-dependencies on  main
➜ helm3 plugin list
NAME       	VERSION   	DESCRIPTION
2to3       	0.8.0     	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
diff       	3.1.3     	Preview helm upgrade changes as a diff
mapkubeapis	0.0.15    	Map release deprecated Kubernetes APIs in-place
```

Thanks a lot.

**Comment by mahgo** [comment] 2021-11-16 23:30
This is something that would be great to have fixed.

**Comment by mumoshu** [comment] 2022-01-09 09:32
@firehist @mahgo Hey! Thanks for reporting. Although I was able to reproduce the exact issue, I'm not sure how this can be fixed.

helm-diff internally uses `helm template`(or `helm upgrade --dry-run` if #330 is enabled) to render the manifests from the chart. FWICS from my own test result, neither `helm template` nor `helm upgrade --dry-run` is unable to take the subchart values into account.

Would you mind confirming?

**Comment by mumoshu** [comment] 2022-01-10 05:37
@firehist I've tried installing your example and run the below:

```
$ helm diff upgrade foo ./helm-diff-dependencies --set argo-cd.nameOverride=testtest
```

This did show a lot of diff due to changes in metadata.name of every resource in the argo-cd dependency:

https://gist.github.com/mumoshu/325631dd11e3fbd1e6d87b37537bcf37

All this seems to imply that it just works, correctly showing diff on the dependency.

I've tried it with both helm 3.5.3 and 3.7.2, with helm-diff 3.1.3 and the edge version of helm-diff build from the current master.

**Comment by mumoshu** [comment] 2022-01-10 05:37
@mahgo Hey! What do you mean by "fixed" here? Did you actually verify that it didn't work as intended for you? Then, would you mind sharing your chart and the command you used to install and diff the release, for reproduction?

**Comment by mahgo** [comment] 2022-01-10 06:17
@mumoshu I guess I didn't consider that handling dependency charts might be out of the scope of this plugin. If this is the case then it might be worth adding to the readme etc.

The main use case for me and this plugin so far has been to determine if upgrading a chart is needed or not.

**Comment by mumoshu** [comment] 2022-01-10 06:23
@mahgo Just to be clear, are you basically saying you didn't actually try it? Then it's okay.

From a maintainer's perspective, `helm-diff upgrade` should be able to show diff on any `helm upgade`. As long as `helm upgrade` supports dependencies, `helm-diff upgrade` should also support dependencies. Shouldn't that be straight enough? 🤔

**Comment by mahgo** [comment] 2022-01-10 06:26
@mumoshu That's correct, I have not tried the given repository. However I have experienced this problem myself.

**Comment by mumoshu** [comment] 2022-01-10 06:26
// I just wanted to know who had real issue(s), because that's required in order to "fix" something.

**Comment by mumoshu** [comment] 2022-01-10 06:27
@mahgo I'd appreciate it if you could give me an example for reproduction, as I couldn't reproduce it. To be extra sure, are you sure how you can set values for sub-charts?

**Comment by mahgo** [comment] 2022-01-10 06:29
Sure I can look into this in the next few days.

**Comment by mahgo** [comment] 2022-01-11 05:06
Tried to replicate it now. It actually works fine! One thing to note is that you need to call `helm dependencies update` before calling `helm diff upgrade test .`. I wonder if past me didn't realize this.

**Comment by mumoshu** [comment] 2022-01-11 05:13
> helm dependencies update

Perhaps you're running helm-diff on a local chart like @firehist has shared with us in the beginning?

Then yes, `helm dep up` or `helm dep build` should be required in order for helm to download dependencies as tarballs. Otherwise helm-template will fail, so is helm-diff.

**Comment by mahgo** [comment] 2022-01-11 05:21
Well, it's more that if you haven't updated the dependencies since changing the version number, it will still compare to the old version, which is exactly the same.

**Comment by mumoshu** [comment] 2022-01-11 05:48
@mahgo Thanks for clarifying! That makes sense.

**Comment by mumoshu** [comment] 2022-01-23 04:52
@firehist @mahgo To summarize, I assume you've just missed updating your local chart's dependencies by explicitly running `helm dep up` and/or `helm dep build`.

I believe it's helm's nature that any local chart's dependencies are downloaded into `./$CHART/charst/*.tar.gz` and they remain there forever and can be outdated until you rerun `helm dep build`. Letting helm-diff automatically detect those outdated chart deps and rerunning `helm dep build` doesn't make much sense to me, as `helm template` or `helm upgrade` doesn't do that.

Correct me if I'm wrong. In the meantime, I'm closing this as not actionable in helm-diff.

Thank you again for reporting!

**Closed by mumoshu** 2022-01-23 04:52 UTC
Labels: invalid
