### ISSUE TITLE
Failed to install helm-diff

### ISSUE THREAD

**Issue by jbunce** [databus23/helm-diff#223] opened 2020-07-20 05:10 UTC
```
helm plugin install https://github.com/databus23/helm-diff --version master      

Failed to install helm-diff
	For support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
```

**Comment by jbunce** [comment] 2020-07-20 05:23
For anybody following along: use `helm plugin install https://github.com/databus23/helm-diff`

**Comment by dackroyd** [comment] 2020-07-20 06:11
The listed command doesn't work if Helm 3 is installed

**Comment by dackroyd** [comment] 2020-07-20 06:14
`HELM_PLUGIN_DIR` only ends up set if Helm v2 is in use: https://github.com/databus23/helm-diff/pull/206/files#diff-4de5a19daf48eac2f11c321271177a1bR12

When fetching tag versions, the git repo being checked is blank string, rather than the plugin dir: https://github.com/databus23/helm-diff/pull/206/files#diff-4de5a19daf48eac2f11c321271177a1bR74

**Comment by jbunce** [comment] 2020-07-20 06:41
`helm plugin install https://github.com/databus23/helm-diff --version e186caafe744378a6059f9b70084b49daf196ede` allows an installation before the regression was introduced

**Comment by arthurk** [comment] 2020-07-20 06:41
Same issue here. 
`helm plugin install https://github.com/databus23/helm-diff --version 26d61fa2aad8476d40307f662db5edd59b07b79b` works as a workaround (this is the rev before a bunch of PRs were merged today)

**Comment by mumoshu** [comment] 2020-07-20 07:28
Thanks everyone.

Turns out my take on this thread was wrong: https://github.com/databus23/helm-diff/pull/206/files#r421447182

So, `: ${BAR:=bar}` does set `BAR` to `bar`. We need to remove `if [ "$HELM_MAJOR_VERSION" = "Client: v2" ]; then` and `fi` in L11 and L13.

Could anyone submit a pull request for that?

**Comment by mumoshu** [comment] 2020-07-20 18:52
I've confirmed that it works for me now. Could anyone double-check?

**Comment by Xtigyro** [comment] 2020-07-20 18:59
```
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630  100   630    0     0   1571      0 --:--:-- --:--:-- --:--:--  1571
100 12.8M  100 12.8M    0     0   740k      0  0:00:17  0:00:17 --:--:--  526k

Yup - tested it with Helm v2.16.9 and v3.2.4.
```

**Comment by mumoshu** [comment] 2020-07-20 19:01
@Surian I feel sorry for breaking it and I can imagine your work may have been affected by this. But it would be great if you could cancel your 👎. It hurts. It makes me lose my motivation!

I'm always trying to do my best and I even replied to this thread in exchange of my break time while working of my primary job. And it's 4AM in my time zone. Hope you won't ask me more 😃

**Comment by mumoshu** [comment] 2020-07-20 19:03
@Xtigyro Much appreciated!

**Comment by mumoshu** [comment] 2020-07-20 19:06
I'm closing this as resolved. Please feel free to reopen or create another issue if it doesn't work in any case.

Thanks everyone for reporting and sharing the workaround.

**Closed by mumoshu** 2020-07-20 19:06 UTC

**Comment by Xtigyro** [comment] 2020-07-20 19:12
@mumoshu Thank you, man! Take some rest. One can please only some people for some time.

You're one of my open-source heros (I mean it - `helmfile` is one of the pillars for me when it comes down to automating the usage of Helm in a production environment).

**Comment by chrw** [comment] 2020-07-21 06:24
Thanks for the fast response to the problem! Great tool! 👍
