### ISSUE TITLE
error calling index: index of untyped nil

### ISSUE THREAD

**Issue by sanzenwin** [databus23/helm-diff#295] opened 2021-07-16 11:02 UTC
```yaml
{{- $secretName := printf "%s" .Values.incomingEmail.password.secret -}}
{{- $incomingEmailPwSecretKey := .Values.incomingEmail.password.key -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
{{- if .Release.IsUpgrade }}
  {{ $incomingEmailPwSecretKey }}: {{ index (lookup "v1" "Secret" .Release.Namespace $secretName).data $incomingEmailPwSecretKey }}
{{ else }} # install operation
  {{ $incomingEmailPwSecretKey }}: {{ randAlphaNum 40 | b64enc }}
{{ end }}

```

`helm diff version: v3.1.3`

After doing `helm install ...` , if I do `helm upgrade ...`, everything is just ok. But when I do `helm diff upgrade ...`, I get this error:

`Error: Failed to render chart: exit status 1: Error: template: setup/templates/incoming-email-secret.yaml:10:38: executing "setup/templates/incoming-email-secret.yaml" at <index (lookup "v1" "Secret" .Release.Namespace $secretName).data $incomingEmailPwSecretKey>: error calling index: index of untyped nil`

**Comment by mumoshu** [comment] 2022-01-09 04:05
@sanzenwin Hey! Does it work with `helm template`? helm-diff internally calls helm-template to render the chart for diff so it won't work if helm-template doesn't work.

**Comment by mumoshu** [comment] 2022-01-09 08:32
To anyone who encountered this- would you mind rerunning helm-diff it with `HELM_DIFF_USE_UPGRADE_DRY_RUN=true` added via #330, see if it fixes the issue, and report the result here?

**Comment by mumoshu** [comment] 2022-01-09 08:57
This looks like a dupe of #263. Let's move.

**Closed by mumoshu** 2022-01-09 08:57 UTC
